packages:
  - packages/*
  - examples/*
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild

catalogs:
  dev:
    "@types/node": 24.10.4
    typescript: 5.9.3
    vite: 7.3.0
    react: 19.2.3
    react-dom: 19.2.3
