export {Component as AlertCircle} from "./icons/AlertCircle.js"
export {Component as AlertTriangle} from "./icons/AlertTriangle.js"
export {Component as Archive} from "./icons/Archive.js"
export {Component as ArrowRight} from "./icons/ArrowRight.js"
export {Component as Settings} from "./icons/Settings.js"
export {Component as SettingsWithFillOptions} from "./icons/SettingsWithFillOptions.js"