import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { describe, test, expect, afterEach } from 'vitest';

const fixturesvgPath = path.join(
  new URL('.', import.meta.url).pathname,
  '__fixtures__/arrow.svg',
);
const arrowSvgContents = fs.readFileSync(fixturesvgPath, 'utf8');

type LoaderFn = (
  this: { getOptions(): Record<string, unknown>; resourcePath: string },
  contents: string,
) => Promise<string>;

// Requires 'pnpm build' before running tests (same as packages/webpack)
// @ts-expect-error -- dist/index.d.cts is generated by the build
const { default: loader } = (await import('../../dist/index.cjs')) as {
  default: LoaderFn;
};

let tempDir: string;

afterEach(() => {
  if (tempDir) fs.rmSync(tempDir, { recursive: true, force: true });
});

async function runLoader(
  options: Record<string, unknown>,
): Promise<{ jsModule: string; assetFilename: string; assetContent: string }> {
  const ctx = {
    getOptions: () => ({ outputDir: tempDir, ...options }),
    resourcePath: fixturesvgPath,
  };
  const jsModule = await loader.call(ctx, arrowSvgContents);
  const files = fs.readdirSync(tempDir);
  const assetFilename = files[0]!;
  const assetContent = fs.readFileSync(path.join(tempDir, assetFilename), 'utf8');
  return { jsModule, assetFilename, assetContent };
}

test('converts *.svg import into a valid JS module with svg[use], using defaults', async () => {
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'svg-use-next-test-'));
  const publicPath = '/_next/static/svgAssets/';
  const { jsModule, assetFilename, assetContent } = await runLoader({ publicPath });

  expect(assetFilename).toMatch(/^arrow-[0-9a-f]{8}\.svg$/);

  expect(jsModule).toMatchInlineSnapshot(
    `
    "import {createThemedExternalSvg} from "@svg-use/react";
      
    export const url = "/_next/static/svgAssets/arrow-501799d3.svg";
    export const id = "use-href-target";
    export const viewBox = "0 0 24 24";

    export const Component = createThemedExternalSvg({url, id, viewBox});"
  `,
  );

  expect(assetContent).toMatchInlineSnapshot(
    `"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="var(--svg-use-color-primary, currentColor)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right" id="use-href-target"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>"`,
  );
});

describe('plugin options', () => {
  test('accepts a custom function to configure a theme', async () => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'svg-use-next-test-'));
    const { assetContent } = await runLoader({
      publicPath: '/_next/static/svgAssets/',
      getThemeSubstitutions: ({
        fills,
        strokes,
      }: {
        fills: Map<string, number>;
        strokes: Map<string, number>;
      }) => {
        if (fills.size > 1 || strokes.size > 1) {
          throw new Error('Only one fill and stroke are supported');
        }
        return {
          fills: new Map(
            Array.from(fills.entries()).map(([k]) => [k, 'var(--my-color-primary)']),
          ),
          strokes: new Map(
            Array.from(strokes.entries()).map(([k]) => [k, 'var(--my-color-primary)']),
          ),
        };
      },
    });

    expect(assetContent).toMatchInlineSnapshot(
      `"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="var(--my-color-primary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right" id="use-href-target"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>"`,
    );
  });

  test('accepts a custom getSvgIdAttribute option', async () => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'svg-use-next-test-'));
    const { assetContent } = await runLoader({
      publicPath: '/_next/static/svgAssets/',
      getSvgIdAttribute: () => 'my-id',
    });

    expect(assetContent).toMatchInlineSnapshot(
      `"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="var(--svg-use-color-primary, currentColor)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right" id="my-id"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>"`,
    );
  });

  test('accepts getThemeSubstitutions: null to disable theming', async () => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'svg-use-next-test-'));
    const { assetContent } = await runLoader({
      publicPath: '/_next/static/svgAssets/',
      getThemeSubstitutions: null,
    });

    // stroke stays as the original 'currentColor' — no CSS variable substitution
    expect(assetContent).toMatchInlineSnapshot(
      `"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right" id="use-href-target"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>"`,
    );
  });
});
