name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for actions/checkout

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ["check-types", "lint", "test"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Build all
        # NOTE: pnpm runs scripts in topological order
        run: pnpm run -r build
      - run: pnpm ${{ matrix.command }}
